# -*- coding: utf-8 -*-
"""ML Capstone Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18OPzcl54RfhDbVlrfsah5gMoc7z7Mp4s

**Part 1 Data Acquisition and Exploratory Data Analysis (EDA)**
"""

#Machine Learning Foundation Capstone Project

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/diabetes.csv")

print("First 5 rows:")
display(df.head())

print("\nData Info:")
print(df.info())

# Descriptive Statistics

print("\nDescriptive Statistics:")
display(df.describe())

# Analyze Target Balance

print("\nTarget Balance (Outcome count):")
print(df["Outcome"].value_counts())
print("\nPercentage Distribution:")
print(df["Outcome"].value_counts(normalize=True) * 100)

#Histogram For Glucose

plt.figure(figsize=(6,4))
sns.histplot(df["Glucose"], bins=30, kde=True, color="blue")
plt.title("Distribution of Glucose")
plt.xlabel("Glucose Level")
plt.ylabel("Frequency")
plt.show()

#Histogram For BMI

plt.figure(figsize=(6,4))
sns.histplot(df["BMI"], bins=30, kde=True, color="green")
plt.title("Distribution of BMI")
plt.xlabel("BMI Level")
plt.ylabel("Frequency")
plt.show()

# Count plot for Outcome

plt.figure(figsize=(6,4))
sns.countplot(x="Outcome", data=df, palette="Set2")
plt.title("Count of Diabetes Outcome")
plt.xlabel("Outcome (0 = Not Diabetic, 1 = Diabetic)")
plt.ylabel("Count")
plt.show()

"""**Part 2 Data Preprocessing and Feature Engineering**"""

# Columns with biologically impossible zeros

zero_columns = ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI"]

# Count suspicious zeros in each column

print("Suspicious Zero Counts:")
for column in zero_columns:
    zero_count = (df[column] == 0).sum()
    print(f"{column}: {zero_count}")

# Replace zeros with median of each column

for column in zero_columns:
    median_value = df[column].median()
    df[column] = df[column].replace(0, median_value)

# Verify cleaning

print("\nAfter imputation, minimum values:")
print(df[zero_columns].min())

# Prepare Data for Modeling and Scaling

X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Train-Test Split (70% train, 30% test)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

# Feature Scaling (Standardization)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

# Fit scaler on training data only

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
print("\nShape of training set:", X_train_scaled.shape)
print("Shape of testing set:", X_test_scaled.shape)

"""**Part 3 Model Training and Evaluation**"""

from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state=42)
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

# Evaluate Performance

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n")
print(cm)

# Visualize Confusion Matrix

plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=['Not Diabetic (0)', 'Diabetic (1)'],
            yticklabels=['Not Diabetic (0)', 'Diabetic (1)'])
plt.title("Confusion Matrix Heatmap")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# Classification Report

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))